name: Crawling
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

jobs:
  crawling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Crawling
        run: yarn start

      - name: Upload
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: data
          CLEAN: false
